apiKey: abcdef_123456
showAppToUsers: false
supportedLanguages:
    - cpp
    - csharp
    - go
    - java
    - javascript
    - python
    - swift
version:
    number: 0
    releaseDate: '2025-05-15'
